#
# SMPItems Configuration File
# Example: zombie: 50
# This has a 1 / 50 chance of spawning a Tubby Zombie
#
# DEFAULT VALUES
# midget: 30
# witherskeleton: 40
# zombie: 50
# skeleton: 60
# spider: 65
# stray: 80
# enderman: 100
# creeper: 130

server:
  mobs:
    spawnrate:
      midget: 30
      witherskeleton: 40
      zombie: 50
      skeleton: 60
      spider: 65
      stray: 80
      enderman: 100
      creeper: 130
  ender_dragon:
    end_world: world_the_end
    frame1:
      x: 0
      y: 0
      z: 0
      occupied: false
    frame2:
      x: 0
      y: 0
      z: 0
      occupied: false
    frame3:
      x: 0
      y: 0
      z: 0
      occupied: false
    frame4:
      x: 0
      y: 0
      z: 0
      occupied: false
  flare_radius: 20.0