name: SMPItems
version: ${project.version}
main: tfsmp.smpitems.SMPItems
api-version: 1.13
authors: [lildarke, lildarkee, fionnn]
description: Items for SMP. Based on https://docs.google.com/spreadsheets/d/1CzddRDa38kimHsFf5tJgeP0CZoR2P5yUBMJwnQJ1LIU/edit
commands:
  smpspawnmob:
    description: Spawn a mob from the SMPItems plugin.
    usage: /<command> <mob>
    aliases: [ssm, spawntubby]
  smpgiveitem:
    description: Give yourself an item from the SMPItems plugin.
    usage: /<command> <item>
    aliases: [sgi, smpgive]
  smpsetframe:
    description: Set the coordinates of a portal frame for the Tubby Ender Dragon.
    usage: /<command> <frameid> <x> <y> <z>
    aliases: [ssf, smpframe]
  smpcredits:
    description: Credits for the plugin.
    usage: /<command>
    aliases: [smpc]